### ISSUE TITLE
看不懂

### ISSUE THREAD

**Issue by SpiritMark** [longxiaonan/java-sea#3]
**请问这个项目主要是干什么的,博主很厉害我想参考学习下**

**Comment by longxiaonan** [comment]
我立这个项目的原因是想整合收集java中的各个技术的整合和实践啊。比如这个项目里面有redis实现分布式锁(目前未完善)，整合mybatis，整合mybatis-plus等等，我们不用去记住每个步骤啊，这个项目的相关子项目下已经实现啦，只要按照readme 复制代码就可以了。
你如果是学习的话可以重点看看javasea-volcano这个子模块的readme。这个是绝大部分公司会用的基于springboot的脚手架。
